name: lua-ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Lua environment
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 luarocks

      - name: Install luacheck via LuaRocks
        run: luarocks install luacheck --local

      - name: Run luacheck
        run: luacheck .

      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Using --check makes the action exit with an error if formatting issues are found.
          args: --check .
          # It is a good idea to pin to a specific version.
          version: latest
